
BEGIN TRAN T_LayThongTinSinhVien
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

EXEC LayThongTinSinhVien '0812001'
WAITFOR DELAY '00:00:05'
EXEC LayThongTinSinhVien '0812001'

COMMIT TRAN T_CapNhatSinhVien