BEGIN TRAN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
DECLARE @sldk INT
SELECT @sldk = SoLuongSVNhom FROM MONHOC WITH (UPDLOCK) 
WHERE MaMonHoc = '3'
SET @sldk = @sldk + 5
WAITFOR DELAY '00:00:05'

UPDATE MONHOC SET SoLuongSVNhom = @sldk WHERE MaDoAn = '2'

COMMIT TRAN