BEGIN TRAN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

SELECT * FROM SINHVIEN WHERE MaSinhVien LIKE '0812001'

WAITFOR DELAY '00:00:05'

SELECT * FROM SINHVIEN WHERE MaSinhVien LIKE '0812001'

COMMIT TRAN